name: Build LaTeX document

on:
  push:
    paths:
      - "docs/*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          working_directory: docs
          extra_system_packages: "inkscape"
      - name: Rename PDF
        run: |
          mv docs/main.pdf report.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: report.pdf
