name: Test Build

on: [push]

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: |
          echo "export const API_FOOTBALL_KEY = ''" >> env.ts
      - run: yarn nx run-many --target=build
